//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Borrow
    {
        public int ID { get; set; }
        public Nullable<int> BookID { get; set; }
        public bool Use { get; set; }
        public Nullable<int> CardID { get; set; }
        public Nullable<System.DateTime> GetTime { get; set; }
        public Nullable<System.DateTime> LoseTime { get; set; }
    
        public virtual Book Book { get; set; }
        public virtual User User { get; set; }
    }
}
